name: Build

on:
  push:
    branches: [ '**' ]
    tags-ignore: ['**' ]

concurrency:
  group: ci-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  windows-msvc:
    name: Windows (MSVC)
    uses: ./.github/workflows/windows-msvc.yml
    secrets: inherit

  windows-ucrt64:
    name: Windows (UCRT64)
    uses: ./.github/workflows/windows-ucrt64.yml
    secrets: inherit

  linux:
    name: Linux (Ubuntu)
    uses: ./.github/workflows/ubuntu.yml
    secrets: inherit
